### PR TITLE
Move linting to first so errors on annotation are less confusing

### PR DESCRIPTION
**Pull request by hbiede**
Just swapped around independent steps

### CODE REVIEW

**Review by jgreazel — APPROVED** [review]

**Review by alehechka — APPROVED** [review]

**Comment by alehechka** [comment]
Can you add @devops to the codeowners for this?

**Comment by hbiede** [comment]
I'm confused why it isn't already. The Code Owners file looks correct

**Review by alehechka — APPROVED** [review]

**Comment by alehechka** [comment]
I wonder if the CODEOWNERS file needs to be merged into main before it gets counted for the PR? Still requiring a review from @dmsi-io/mobile

**Comment by hbiede** [comment]
It does. CODEOWNERS only applies when its on the default branch

**Review by brianspowers — APPROVED** [review]

**Pull request merged**
